<?php

/**
 * @file
 * Contains event_config.module.
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 */
function event_config_preprocess_html(&$variables) {
  $config = \Drupal::config('event_config.settings');
  $variables['background_color'] = new Attribute(['style' => 'background-color: ' . $config->get('background_color') . ';']);
}

/**
 * Implements hook_preprocess_HOOK() for node templates.
 */
function event_config_preprocess_node(&$variables) {
  if ($variables['view_mode'] == 'teaser') {
    $variables['background_color'] = new Attribute(['style' => 'background-color: ' . \Drupal::state()->get('event_config.background_color') . ';']);
    $variables['card_color'] = new Attribute(['style' => 'background-color: ' . \Drupal::state()->get('event_config.card_color') . ';']);
  }
}
